version: "3"
services:
  app:
    container_name: khmer_ocr_dev
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    ports:
      - 80:3000
      - 8000:8000
    volumes:
      - .:/app
